main: de.raidcraft.betonquestbridge.RCBetonQuestBridgePlugin
name: RCBetonQuestBridge
version: ${project.version}#${build.number}
description: Implementation of a Beton Quest <-> RaidCraft Plugins bridge.
author: Silthus
website: http://www.raid-craft.de
depend: [RaidCraft-API, BetonQuest]
database: false